name: Type generation

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17
      - name: Generate Paper types
        run: |
          java -jar java-ts-bind-all.jar --packageJson paper/package.json
      - uses: actions/setup-node@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Publish to npm
        if: ${{ github.ref == 'refs/heads/master' }}
        run: |
          sed -i "s/GIT_SHA/$(git rev-parse --short $GITHUB_SHA)/g" */package.json || true # Fails for .github otherwise
          npm publish --access=public paper
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}